### PR TITLE
Replace true/false with Yes/No for consistency

### PR DESCRIPTION
**Pull request by rigwild**
`true` and `false` were set instead of `Yes` and `No` like in other pages.

Just to keep consistensy.

the `bridgechains.md` diffs seems to be bugged. I can't figure out why. The file is stil there though (view file).

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by faustbrian** [comment]
@rigwild conflicts

**Comment by rigwild** [comment]
Deleted source repo. Don't have write access here anymore.

```sh
git fetch origin pull/7/boolean-to-yes-no

git remote add fork-rigwild https://github.com/rigwild/gitbooks-api.git

git checkout remotes/origin/pr/7
git pull fork-rigwild boolean-to-yes-no

git remote rm fork-rigwild
```

**Comment by ghost** [comment]
Your pull request has been closed, thank you for trying to solve an issue. If you think it was closed prematurely please provide additional information.

**Pull request closed without merging**
